global:
  scrape_interval: 15s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'snmp_exporter_ilo'
    file_sd_configs:
      - files :
        - /etc/prometheus/servers.yml
    metrics_path: /snmp
    params:
      module: [ilo] #which OID's we will be querying in
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 10.30.30.11:9116  # The SNMP exporter's real hostname:port.

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
